# Imagen de PHP con Apache
FROM php:8.1-apache

# Evita preguntas interactivas durante apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Instalar dependencias necesarias y las extensiones de PostgreSQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiar el código del proyecto al contenedor
COPY . /var/www/html/

# Exponer el puerto 80
EXPOSE 80